global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'shortener'
    metrics_path: /metrics
    static_configs:
      - targets: ['shortener:8001']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'click_analytics'
    static_configs:
      - targets: [ 'click-analytics:8088' ]
