# pyproject.toml

[tool.black]
line-length = 99
target-version = ["py39"]  # Adjust to your Python version as needed

[tool.isort]
profile = "black"
line_length = 99  # Use underscore instead of hyphen
known_third_party = ["flask", "requests"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"

[tool.ruff]
line-length = 99
exclude = ["migrations", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "W", "B", "C"]
ignore = ["E501", "F401"]
